import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const root=new URL('../',import.meta.url);
const html=readFileSync(new URL('chemistry/index.html',root),'utf8');
const inv=JSON.parse(readFileSync(new URL('chemistry/educator-inventory.json',root),'utf8'));
const scope=JSON.parse(readFileSync(new URL('chemistry/scope.json',root),'utf8'));
for(const term of ['CHEM 101','General Chemistry I','الفصل الأول','Topic → Arena','Exam DNA','General Chemistry with Franklin Ow','مسار الكتب','Educator','Pearson+']) assert.ok(html.includes(term),`missing ${term}`);
assert.equal(scope.course_code,'CHEM 101');
assert.equal(scope.arena_targets.length,9);
assert.equal(scope.exam_dna_status,'PENDING_PAST_EXAMS_OR_INSTRUCTOR_MATERIALS');
assert.equal(inv.lesson_count,24);
assert.equal(inv.clusters.length,14);
assert.equal(inv.lessons.length,24);
assert.equal(inv.status,'SOURCE_INVENTORY_ONLY');
assert.ok(inv.rule.includes('not the semester syllabus'));
assert.equal(new Set(inv.lessons.map(x=>x.n)).size,24);
assert.deepEqual(inv.lessons.map(x=>x.n),Array.from({length:24},(_,i)=>i+1));
assert.equal(scope.educator_map['22'],'ACTIVE_CORE');
assert.equal(scope.educator_map['24'],'OUTSIDE_EXPLICIT_SCOPE');
assert.ok(!html.includes('best source'));
console.log('CHEM 101 checks passed: official scope locked, 9 Arena targets, 24 Educator lessons mapped across 14 clusters.');
