import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const root=new URL('../ma101/',import.meta.url);
const html=readFileSync(new URL('index.html',root),'utf8');
assert.match(html,/https:\/\/isharataljasad\.com\/ma101\//);
for(const term of ['Adaptive Learning Arena','المشرف الذكي','Topic = Arena','Exam DNA','Challenge','Mastery','Resource Reservoirs','اسأل المشرف في ChatGPT']) assert.ok(html.includes(term),`missing ${term}`);
assert.ok(html.includes('لا يصدر «درجة ذكاء»'));
assert.ok(html.includes('science-ma101-arena-v2'));
assert.ok(html.includes('failures'));
assert.ok(html.includes('mastered'));
assert.ok(html.includes('chatgpt.com/?q='));
const ctx={window:{}};vm.createContext(ctx);
for(const f of ['nodes-1.js','nodes-2.js','nodes-3.js','nodes-4.js']) vm.runInContext(readFileSync(new URL(f,root),'utf8'),ctx);
const nodes=Array.from(ctx.window.MA101_NODES);
assert.equal(nodes.length,33);
assert.equal(new Set(nodes.map(x=>x.id)).size,33);
assert.equal(JSON.stringify(nodes.map(x=>x.id)),JSON.stringify(Array.from({length:33},(_,i)=>`C${i+1}`)));
assert.equal(nodes.every(x=>x.url?.startsWith('https://openstax.org/books/calculus-volume-1/pages/')),true);
assert.equal(nodes.every(x=>x.goal&&x.stop&&x.practice&&x.pass),true);
assert.equal(nodes.reduce((a,x)=>a+x.mins,0),1985);
const counts=nodes.reduce((a,x)=>(a[x.source]=(a[x.source]||0)+1,a),{});
assert.equal(JSON.stringify(counts),JSON.stringify({E:26,P:4,O:2,S:1}));
const banned=['Definite Integral','Fundamental Theorem of Calculus','Integration by Parts','Sequences and Series','Separable Differential Equations'];
for(const term of banned) assert.equal(JSON.stringify(nodes).includes(term),false,`MA102 leakage: ${term}`);
console.log('MA 101 Arena checks passed: adaptive supervisor shell, 33 concepts, 14 weeks, 1985 reading minutes.');
