(()=>{'use strict';
const key='science.chem.atomic.v2';
const P=[
{q:'ذرة متعادلة عددها الذري 17 وعددها الكتلي 35. كم نيوترونًا في نواتها؟',o:['17','18','35','52'],a:1,s:'mass',hint:'عدد النيوترونات = العدد الكتلي − عدد البروتونات.'},
{q:'ذرتان لهما 6 بروتونات، لكن الأولى 6 نيوترونات والثانية 8. ما العلاقة بينهما؟',o:['عنصران مختلفان','نظيران للعنصر نفسه','أيونان متساويان','لهما العدد الكتلي نفسه'],a:1,s:'isotope',hint:'العنصر يتحدد بعدد البروتونات؛ اختلاف النيوترونات يصنع نظائر.'},
{q:'أيون يضم 12 بروتونًا و10 إلكترونات. ما شحنته؟',o:['2−','متعادل','2+','12+'],a:2,s:'charge',hint:'فائض بروتونين موجبين على الإلكترونات السالبة يعني +2.'},
{q:'أي قيمة تحدد هوية العنصر ولو تغيّر عدد نيوتروناته؟',o:['العدد الكتلي','عدد البروتونات','عدد النيوترونات','كتلة العينة'],a:1,s:'isotope',hint:'العدد الذري هو عدد البروتونات.'}
];
const T=[
{q:'تحقق مستقل: ذرة محايدة بها 15 بروتونًا وكتلتها العددية 31؛ كم نيوترونًا؟',o:['15','16','31','46'],a:1,s:'mass',hint:'اطرح البروتونات من العدد الكتلي.'},
{q:'تحقق مستقل: أيون Al³⁺ وعدده الذري 13؛ كم إلكترونًا بقي لديه؟',o:['16','13','10','3'],a:2,s:'charge',hint:'فقد 3 إلكترونات من 13.'},
{q:'تحقق بديل: نظير الكلور عدده الذري 17 والكتلي 37؛ كم نيوترونًا؟',o:['17','20','37','54'],a:1,s:'mass',hint:'37 − 17 = ؟'},
{q:'تحقق بديل: أيون لديه 9 بروتونات و10 إلكترونات؛ ما شحنته؟',o:['1−','1+','0','9+'],a:0,s:'charge',hint:'إلكترون إضافي واحد يضيف شحنة −1.'}
];
const $=id=>document.getElementById(id);const fresh=()=>({phase:'practice',i:0,ti:0,correct:0,wrong:0,streak:0,misses:{},focus:'',await:false});let s=fresh();try{const stored=JSON.parse(localStorage.getItem(key)||'null');if(stored&&['practice','transfer','remediate','needs_review','passed'].includes(stored.phase))s={...fresh(),...stored,await:false}}catch{};
function save(){try{localStorage.setItem(key,JSON.stringify({...s,await:false}))}catch{}};
function metrics(){$('stage').textContent=({practice:'تدريب',transfer:'تحقق جديد',remediate:'علاج موجه',needs_review:'يحتاج مراجعة',passed:'إتقان مثبت'})[s.phase];$('errors').textContent=s.wrong;$('streak').textContent=s.streak;$('bar').style.width=(s.phase==='passed'?100:s.phase==='practice'?s.i*12:s.phase==='transfer'?50+s.correct*25:50)+'%'}
function resource(skill){$('res').hidden=false;$('resText').textContent=skill==='charge'?'راجع الشحنة: البروتون +1 والإلكترون −1. Goldwhite Lesson 03، The Chemist’s Atom، ثم ارجع إلى تحدي الأيون.':'Goldwhite Lesson 03، The Chemist’s Atom، 15:10–22:21: ميّز بين العدد الذري والكتلي، ثم احسب النيوترونات أو حدّد النظائر.'}
function show(){metrics();$('feedback').hidden=true;$('res').hidden=true;$('next').hidden=true;s.await=false;$('options').replaceChildren();if(['passed','remediate','needs_review'].includes(s.phase)){const msg={passed:'أجبت عن سؤالين جديدين متتاليين دون مساعدة. هذا إتقان مُلاحظ داخل هذه الساحة، لا توقع لدرجة الامتحان.',remediate:'لم تنجح في التحقق الجديد. ادرس المهارة المحددة، ثم استخدم نموذجَي تحقق بديلين.',needs_review:'لم تنجح في التحقق البديل أيضًا. لا نعلن الإتقان: راجع المصدر أو اسأل المعلم، ثم ابدأ تدريبًا جديدًا.'};$('question').textContent=msg[s.phase];$('qNumber').textContent='نتيجة المحاولة';if(s.phase==='remediate'){resource(s.focus);$('next').hidden=false;$('next').textContent='بدأ التحقق البديل'}if(s.phase==='needs_review')resource(s.focus);$('supervisor').textContent='المشرف: '+msg[s.phase];save();return}
const transfer=s.phase==='transfer',q=transfer?T[s.ti]:P[s.i];if(!q){s.phase='transfer';s.ti=0;s.correct=0;save();show();return}$('qNumber').textContent=transfer?'اختبار نقل المهارة · '+(s.correct+1)+'/2':'تحدّي · '+(s.i+1)+'/4';$('question').textContent=q.q;q.o.forEach((answer,i)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.textContent=answer;b.onclick=()=>choose(i);$('options').append(b)});$('supervisor').textContent=transfer?'المشرف: إجابتان مستقلتان على أرقام جديدة؛ أي خطأ يُعيدك للعلاج.':'المشرف: جرّب قبل مشاهدة المحاضرة. نعالج نمط الخطأ لا نعيد الدرس كله.';save()}
function choose(v){if(s.await)return;const transfer=s.phase==='transfer',q=transfer?T[s.ti]:P[s.i];s.await=true;$('options').querySelectorAll('button').forEach(b=>b.disabled=true);$('feedback').hidden=false;$('next').hidden=false;if(v===q.a){s.streak++;$('feedback').textContent='صحيح: '+(transfer?'نتيجة مستقلة في مسألة جديدة.':'أكملت هذه الفكرة؛ تابع.');$('feedback').className='feedback';if(transfer){s.correct++;if(s.correct===2){s.phase='passed';$('next').textContent='عرض نتيجة الإتقان'}else{s.ti++;$('next').textContent='سؤال التحقق التالي'}}else{s.i++;$('next').textContent=s.i>=P.length?'ابدأ التحقق المستقل':'التحدي التالي'}}else{s.wrong++;s.streak=0;s.focus=q.s;s.misses[q.s]=(s.misses[q.s]||0)+1;$('feedback').textContent='تصحيح موجّه: '+q.hint;$('feedback').className='feedback error';resource(q.s);if(transfer){s.phase=s.ti>=2?'needs_review':'remediate';$('next').textContent=s.phase==='remediate'?'افتح العلاج':'عرض توصية المراجعة'}else{$('next').textContent='حاول السؤال مرة أخرى';$('supervisor').textContent='المشرف: راجع مهارة '+q.s+' فقط، ثم حاول مرة ثانية؛ لا نعدّ التصحيح دليل إتقان.'}}metrics();save()}
$('next').onclick=()=>{if(s.phase==='remediate'){s.phase='transfer';s.ti=2;s.correct=0}else if(s.phase==='needs_review'){show();return}else if(s.phase==='passed'){show();return}show()};$('restart').onclick=()=>{if(confirm('إعادة الساحة ومسح التقدّم المحلي؟')){s=fresh();try{localStorage.removeItem(key)}catch{}show()}};
$('copy').onclick=async()=>{const question=$('query').value.trim();if(!question){$('copyStatus').textContent='اكتب سؤالك أولًا.';return}const prompt='Act as a Socratic CHEM 101 tutor. Arena A1 Atomic Structure. Learner phase: '+s.phase+'. Errors: '+s.wrong+'. Current weak skill: '+(s.focus||'not yet known')+'. References: Goldwhite Lesson 03; Franklin Ow Lesson 03; OpenStax Chemistry 2e 2.1–2.3. Ask one targeted diagnostic question, then explain only the missing micro-skill. Do not reproduce paid transcripts. Do not claim these practice questions predict an official exam. My question: '+question;try{await navigator.clipboard.writeText(prompt);$('copyStatus').textContent='نُسخ السياق؛ الصقه في ChatGPT.'}catch{$('query').value=prompt;$('copyStatus').textContent='انسخ النص من المربع يدويًا.'}};show();
})();