(()=>{'use strict';
const key='science.chem.atomic.v2';
const P=[
{q:"A neutral atom has an atomic number of 17 and a mass number of 35. How many neutrons does it have in its nucleus?",o:['17','18','35','52'],a:1,s:'mass',hint:"Number of neutrons = Mass number − Number of protons."},
{q:"Two atoms each have 6 protons. One has 6 neutrons and the other has 8. How are they related?",o:["Two different elements","Two isotopes of the same element","Two identical ions","They have the same mass number"],a:1,s:'isotope',hint:"An element is determined by the number of protons; Different neutrons make isotopes."},
{q:"An ion has 12 protons and 10 electrons. What is its charge?",o:['2−',"Neutral",'2+','12+'],a:2,s:'charge',hint:"The excess of two positive protons over the negative electrons means +2."},
{q:"Which value determines the identity of the element even if the number of its neutrons changes?",o:["Mass number","Number of protons","Number of neutrons","sample mass"],a:1,s:'isotope',hint:"The atomic number is the number of protons."}
];
const T=[
{q:"Transfer check: a neutral atom has 15 protons and mass number 31. How many neutrons does it have?",o:['15','16','31','46'],a:1,s:'mass',hint:"Subtract the protons from the mass number."},
{q:"Transfer check: Al³⁺ has atomic number 13. How many electrons does the ion have?",o:['16','13','10','3'],a:2,s:'charge',hint:"A neutral aluminium atom has 13 electrons; forming Al³⁺ removes 3."},
{q:"Alternative verification: Chlorine isotope with atomic number 17 and mass 37; How many neutrons?",o:['17','20','37','54'],a:1,s:'mass',hint:'37 − 17 = ?'},
{q:"Alternate check: an ion has 9 protons and 10 electrons. What is its charge?",o:['1−','1+','0','9+'],a:0,s:'charge',hint:"One extra electron adds charge to −1."}
];
const $=id=>document.getElementById(id);const fresh=()=>({phase:'practice',i:0,ti:0,correct:0,wrong:0,streak:0,misses:{},focus:'',await:false});let s=fresh();try{const stored=JSON.parse(localStorage.getItem(key)||'null');if(stored&&['practice','transfer','remediate','needs_review','passed'].includes(stored.phase))s={...fresh(),...stored,await:false}}catch{};
function save(){try{localStorage.setItem(key,JSON.stringify({...s,await:false}))}catch{}};
function metrics(){$('stage').textContent=({practice:"Training",transfer:"New verification",remediate:"Targeted review",needs_review:"Needs review",passed:"Transfer checks passed"})[s.phase];$('errors').textContent=s.wrong;$('streak').textContent=s.streak;$('bar').style.width=(s.phase==='passed'?100:s.phase==='practice'?s.i*12:s.phase==='transfer'?50+s.correct*25:50)+'%'}
function resource(skill){$('res').hidden=false;$('resText').textContent=skill==='charge'?"Review the charge: proton +1 and electron −1. Goldwhite Lesson 03, The Chemist’s Atom, then return to the ion challenge.":"Goldwhite Lesson 03, The Chemist’s Atom, 15:10–22:21: Distinguish between atomic and mass numbers, then count neutrons or identify isotopes."}
function show(){metrics();$('feedback').hidden=true;$('res').hidden=true;$('next').hidden=true;s.await=false;$('options').replaceChildren();if(['passed','remediate','needs_review'].includes(s.phase)){const msg={passed:"You answered two transfer questions correctly in succession. This is a limited practice result, not a mastery assessment or a prediction of your exam grade.",remediate:"The new verification failed. Study the specific skill, then use two alternative verification forms.",needs_review:"It didn't pass the alternate verification either. We don't declare mastery: check the source or ask the teacher, then start a new practice."};$('question').textContent=msg[s.phase];$('qNumber').textContent="Result of the attempt";if(s.phase==='remediate'){resource(s.focus);$('next').hidden=false;$('next').textContent="Start alternate transfer checks"}if(s.phase==='needs_review')resource(s.focus);$('supervisor').textContent="Admin: "+msg[s.phase];save();return}
const transfer=s.phase==='transfer',q=transfer?T[s.ti]:P[s.i];if(!q){s.phase='transfer';s.ti=0;s.correct=0;save();show();return}$('qNumber').textContent=transfer?"Skill transfer test "+(s.correct+1)+'/2':"Challenge · "+(s.i+1)+'/4';$('question').textContent=q.q;q.o.forEach((answer,i)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.textContent=answer;b.onclick=()=>choose(i);$('options').append(b)});$('supervisor').textContent=transfer?"Moderator: Two independent answers to new numbers; Any mistake will send you back to treatment.":"Moderator: Try it before watching the lecture. We address the error pattern and do not repeat the entire lesson.";save()}
function choose(v){if(s.await)return;const transfer=s.phase==='transfer',q=transfer?T[s.ti]:P[s.i];s.await=true;$('options').querySelectorAll('button').forEach(b=>b.disabled=true);$('feedback').hidden=false;$('next').hidden=false;if(v===q.a){s.streak++;$('feedback').textContent="Correct: "+(transfer?"An independent result in a new problem.":"This answer is correct. Continue to the next question.");$('feedback').className='feedback';if(transfer){s.correct++;if(s.correct===2){s.phase='passed';$('next').textContent="View practice result"}else{s.ti++;$('next').textContent="Next verification question"}}else{s.i++;$('next').textContent=s.i>=P.length?"Start independent verification":"Next challenge"}}else{s.wrong++;s.streak=0;s.focus=q.s;s.misses[q.s]=(s.misses[q.s]||0)+1;$('feedback').textContent="Directed correction: "+q.hint;$('feedback').className='feedback error';resource(q.s);if(transfer){s.phase=s.ti>=2?'needs_review':'remediate';$('next').textContent=s.phase==='remediate'?"Open targeted review":"View review recommendation"}else{$('next').textContent="Try the question again";$('supervisor').textContent="Supervisor: See skill "+q.s+" Just, then try again; We do not consider correction to be evidence of mastery."}}metrics();save()}
$('next').onclick=()=>{if(s.phase==='remediate'){s.phase='transfer';s.ti=2;s.correct=0}else if(s.phase==='needs_review'){show();return}else if(s.phase==='passed'){show();return}show()};$('restart').onclick=()=>{if(confirm("Restart this arena and clear its saved progress?")){s=fresh();try{localStorage.removeItem(key)}catch{}show()}};
$('copy').onclick=async()=>{const question=$('query').value.trim();if(!question){$('copyStatus').textContent="Write your question first.";return}const prompt='Act as a Socratic CHEM 101 tutor. Arena A1 Atomic Structure. Learner phase: '+s.phase+'. Errors: '+s.wrong+'. Current weak skill: '+(s.focus||'not yet known')+'. References: Goldwhite Lesson 03; Franklin Ow Lesson 03; OpenStax Chemistry 2e 2.1–2.3. Ask one targeted diagnostic question, then explain only the missing micro-skill. Do not reproduce paid transcripts. Do not claim these practice questions predict an official exam. My question: '+question;try{await navigator.clipboard.writeText(prompt);$('copyStatus').textContent="Context copied. Paste it into ChatGPT."}catch{$('query').value=prompt;$('copyStatus').textContent="Copy the text from the box manually."}};show();
})();