export default {
 id:'chemical-naming',title:'Writing formulas and naming compounds',
 intro:'A name and a formula describe the same chemical composition in different ways. Decide first whether the substance is ionic or molecular; the naming rules depend on that choice. The aim is to account for both atom counts and electric charge.',
 ideas:[
  '**Ionic compounds** contain cations and anions in a ratio with total charge zero. Write the cation first. Use the lowest whole-number ratio of complete ions that gives neutrality; keep every polyatomic ion intact. Calcium Ca²⁺ and chloride Cl⁻ give CaCl₂. Calcium and nitrate NO₃⁻ give Ca(NO₃)₂: parentheses show two whole nitrate ions. Do not reduce the internal subscripts of an ion such as peroxide O₂²⁻.',
  'For an ionic name, name the cation followed by the anion. A one-element anion ends in **-ide**: chloride, oxide, sulfide. A polyatomic ion keeps its established name: nitrate, sulfate, hydroxide. Metals with more than one common charge need a Roman numeral identifying the charge: iron(II) means Fe²⁺; iron(III) means Fe³⁺. The numeral is not an atom count. Metals with a usual fixed charge, such as sodium or calcium, ordinarily do not need it.',
  '**Binary molecular compounds** made from two nonmetals usually use prefixes to state atom counts: mono 1, di 2, tri 3, tetra 4, penta 5, hexa 6. The first element normally omits mono; the second ends in -ide and includes its prefix. Standard vowel contractions give monoxide and pentoxide. CO is carbon monoxide; CO₂ is carbon dioxide. A molecular formula is not reduced to its empirical ratio.',
  'Names must also preserve the chemical context. HCl(g) is hydrogen chloride; HCl(aq) is hydrochloric acid. Common introductory oxyacid names follow the anion: nitrate → nitric acid, nitrite → nitrous acid, sulfate → sulfuric acid. These patterns supplement a table of known ions; they do not let you invent an unknown ion’s formula.',
 ],
 symbols:[['superscript charge','net ion charge; sign and magnitude','multiples of elementary charge'],['subscript','number of atoms or intact ion groups in a formula','count'],['Roman numeral','metal ion charge in an ionic name','positive integer'],['(aq), (s), (l), (g)','aqueous, solid, liquid and gas states','state labels']],
 formulas:[
  {name:'Charge balance for an ionic formula',f:'Σ (number of each ion × signed ion charge) = 0',when:'For a neutral compound, not for an isolated charged ion.'},
  {name:'Two-ion ratio',f:'a q_{cation} + b q_{anion} = 0',when:'a and b are positive whole numbers in the lowest ratio of intact ions. A polyatomic ion’s internal formula stays unchanged.'},
  {name:'Charge from a known formula',f:'metal charge = {{total negative charge magnitude|number of metal ions}}',when:'Applies here when all metal ions have the same charge and the anion charge is known. Mixed-valence compounds require more information.'},
 ],
 table:{caption:'Useful ions for introductory formulas',head:['Cation','Charge','Anion','Charge'],rows:[['sodium, Na⁺','+1','chloride, Cl⁻','−1'],['calcium, Ca²⁺','+2','nitrate, NO₃⁻','−1'],['aluminium, Al³⁺','+3','sulfate, SO₄²⁻','−2'],['ammonium, NH₄⁺','+1','carbonate, CO₃²⁻','−2'],['iron(II), Fe²⁺','+2','hydroxide, OH⁻','−1'],['iron(III), Fe³⁺','+3','phosphate, PO₄³⁻','−3']]},
 examples:[
  {title:'Write a formula from two ionic charges',problem:'Write the formula and name for a compound containing Al³⁺ and SO₄²⁻.',steps:[['Two Al³⁺ ions give +6; three SO₄²⁻ ions give −6.','The smallest common charge magnitude is 6.'],['Write Al₂(SO₄)₃.','Three sulfate groups require parentheses around the complete ion.'],['Name: aluminium sulfate.','Aluminium has its usual +3 charge; sulfate retains its ion name.']],result:'Al₂(SO₄)₃, aluminium sulfate.',meaning:'It contains two Al, three S and twelve O atoms per formula unit. AlSO₄ would carry a net +1 charge and is not the neutral formula.'},
  {title:'Recover a metal charge from a formula',problem:'Name FeCl₂ and FeCl₃.',steps:[['Each chloride is Cl⁻. In FeCl₂, two chlorides contribute −2, so Fe is +2.','The total must be zero.'],['In FeCl₃, three chlorides contribute −3, so Fe is +3.','The number of Fe ions is one in both formulas.'],['Use iron(II) chloride and iron(III) chloride.','The Roman numeral distinguishes two different metal-ion charges.']],result:'FeCl₂: iron(II) chloride. FeCl₃: iron(III) chloride.',meaning:'Iron trichloride can occur in other naming conventions, but the charge-based ionic convention used here clearly identifies Fe³⁺.'},
  {title:'Preserve a polyatomic cation',problem:'Write the formula of ammonium carbonate.',steps:[['Ammonium is NH₄⁺; carbonate is CO₃²⁻.','Retrieve each complete ion and its charge.'],['Two ammonium ions balance one carbonate: 2(+1) + (−2) = 0.','Use the smallest neutral ratio of ions.'],['Write (NH₄)₂CO₃.','The outside 2 multiplies both N and H within ammonium.']],result:'(NH₄)₂CO₃.',meaning:'There are 2 N, 8 H, 1 C and 3 O atoms per formula unit. The subscript does not apply only to H.'},
  {title:'Molecular prefixes preserve the actual formula',problem:'Name N₂O₄ and write the formula for carbon dioxide.',steps:[['N₂O₄ has two N and four O atoms: dinitrogen tetroxide.','The prefix tetra contracts before oxide in the conventional name.'],['Carbon dioxide has one C and two O atoms: CO₂.','No mono is normally used for the first element.'],['Keep N₂O₄ as the molecular formula; NO₂ is its empirical formula.','Reducing the ratio loses the actual counts in one molecule.']],result:'N₂O₄ is dinitrogen tetroxide; carbon dioxide is CO₂.',meaning:'Use molecular prefixes for molecular composition, not instead of charge balance in ordinary ionic names.'},
  {title:'An acid name depends on its state',problem:'Distinguish HCl(g), HCl(aq) and HNO₃(aq).',steps:[['HCl(g) is hydrogen chloride; HCl(aq) is hydrochloric acid.','The aqueous acid name describes hydrogen chloride dissolved in water.'],['HNO₃(aq) is nitric acid; the associated anion is nitrate, NO₃⁻.','The common -ate to -ic acid pattern applies.']],result:'Hydrogen chloride gas; hydrochloric acid solution; nitric acid solution.',meaning:'A state label can change the appropriate name, so do not drop it when it conveys essential information.'},
 ],
 mistakes:[['A Roman numeral gives the number of metal atoms.','It gives the charge of that metal ion in this convention.'],['Cross the charge numbers without checking.','Verify neutrality and reduce the ratio of complete ions. Keep the internal formula of polyatomic ions intact.'],['Reduce all molecular formulas.','A molecular formula states actual counts, even when a simpler empirical ratio exists.'],['Treat every formula containing only nonmetals as molecular.','Ammonium salts contain the polyatomic cation NH₄⁺ and are ionic; identify the species first.']],
 sources:[{title:'OpenStax Chemistry 2e — Chemical nomenclature',url:'https://openstax.org/books/chemistry-2e/pages/2-7-chemical-nomenclature'}],
 checks:[['aluminium sulfate charge',2*3+3*(-2),0,0],['sulfate oxygen count',3*4,12,0],['ammonium carbonate charge',2*1-2,0,0],['ammonium hydrogen count',2*4,8,0],['iron dichloride charge',2+2*(-1),0,0],['iron trichloride charge',3+3*(-1),0,0]],
};
