import {svg,text,line,circle} from '../svg.mjs';
export default {
 id:'intermolecular-forces',title:'Intermolecular forces, phases and solubility',
 intro:'A covalent bond holds atoms together inside a molecule. Intermolecular attractions act between molecules. This distinction explains why a liquid can boil without changing each molecule’s chemical formula.',
 ideas:[
  '**London dispersion forces** arise from fluctuating electron distributions and induced dipoles. They occur between all atoms and molecules, including non-polar ones. Greater polarisability and more effective contact between molecules can make these attractions stronger. Molar mass is a useful comparison within some related families, but it is not a universal rule.',
  '**Dipole–dipole attractions** occur between molecules with permanent dipoles. All such molecules also have dispersion forces. Shape matters: CO₂ contains polar C=O bonds, but its bond dipoles cancel, so an isolated CO₂ molecule has no permanent net dipole. Do not assign a molecule’s polarity from one bond alone.',
  'In the usual introductory model, **hydrogen bonding** needs a donor H covalently bonded to N, O or F and a suitable lone pair on an acceptor, commonly N, O or F. Water can both donate and accept. An ether can accept a hydrogen bond from water but cannot donate one because its hydrogens are bonded to carbon. Hydrogen bonds between molecules are not the covalent O–H bonds inside those molecules.',
  '**Ion–dipole attractions** occur between an ion and a polar molecule. Water’s partially negative oxygen points towards a cation; its partially positive hydrogens point towards an anion. This helps stabilise dissolved ions. Dissolution still depends on the balance of separating the original particles, forming new interactions and the entropy change. Hydration alone does not guarantee that every salt is soluble.',
  'For comparable molecular substances, stronger net intermolecular attractions often mean higher boiling temperature, lower equilibrium vapour pressure at the same temperature, and larger energy required for vaporisation. Comparisons need the same external pressure for boiling points. Molecular size, shape and the set of interactions all matter; there is no fixed ranking that works for every pair of substances.',
  'A liquid boils when its equilibrium vapour pressure equals the external pressure. Lower external pressure allows boiling at a lower temperature. Evaporation can occur below the boiling temperature. In vaporising molecular water, molecules become widely separated but remain H₂O; making H₂ and O₂ would be a chemical reaction with a different energy requirement.',
 ],
 symbols:[['δ+ and δ−','partial atomic charges in a polar bond','not integer ionic charges'],['ΔH_{vap}','molar enthalpy of vaporisation at stated conditions','kJ/mol'],['n','amount vaporised','mol'],['q','heat absorbed for the stated change','kJ'],['P_{vap}','equilibrium vapour pressure at a given temperature','pressure']],
 formulas:[
  {name:'Heat for vaporisation',f:'q = nΔH_{vap}',when:'For vaporising the stated amount at the specified phase-change temperature and pressure. This excludes heating the liquid to that temperature and heating the vapour afterwards.'},
  {name:'Boiling condition',f:'P_{vap}(T_{boil}) = P_{external}',when:'Equilibrium boiling condition; the boiling temperature depends on external pressure.'},
  {name:'Separate heating from a phase change',f:'q_{total} = mc_{p}ΔT + nΔH_{vap}',when:'For a simple path that first warms a liquid to its boiling point, then fully vaporises it; approximate cₚ as constant over the interval. Additional stages need additional terms.'},
 ],
 figure:{svg:svg('support-hbond',{w:500,h:230,title:'A hydrogen bond connects two different water molecules',desc:'Two water molecules are shown. Solid lines are covalent oxygen–hydrogen bonds within each molecule. A dashed line runs from a hydrogen of the left molecule to the oxygen of the right molecule; it represents an intermolecular hydrogen bond. Partial charges label the donor hydrogen positive and the acceptor oxygen negative.'},
  text(90,130,'O',{size:28})+text(166,130,'H',{size:24})+text(52,178,'H',{size:24})
  +line(114,120,156,120,{width:3})+line(90,138,70,159,{width:3})
  +text(310,130,'O',{size:28})+text(390,91,'H',{size:24})+text(390,171,'H',{size:24})
  +line(337,116,382,88,{width:3})+line(337,132,382,158,{width:3})
  +line(192,120,299,120,{color:'#355b90',width:2,dash:'5 5'})
  +text(180,94,'δ+',{size:15})+text(319,94,'δ−',{size:15})
  +text(32,35,'Solid: covalent bonds within each H₂O molecule',{size:15})
  +text(70,208,'Dashed: attraction between two molecules',{size:15})),caption:'The donor hydrogen remains covalently attached to its own oxygen. The dashed hydrogen bond is a separate attraction to the neighbouring molecule.'},
 table:{caption:'Identify the particles and all relevant attractions',head:['Substance or mixture','Particle type','Important attractions'],rows:[['CH₄, pure','Non-polar molecules','Dispersion'],['HCl, pure','Polar molecules','Dispersion and dipole–dipole'],['H₂O, pure','Polar molecules with O–H bonds','Dispersion, dipole–dipole and hydrogen bonding'],['Na⁺ in water','Ion surrounded by polar water','Ion–dipole hydration'],['NaCl crystal','Ionic lattice','Ion–ion electrostatic interactions; not a molecular liquid']]},
 examples:[
  {title:'Compare two molecules with the same molecular formula',problem:'Ethanol CH₃CH₂OH and dimethyl ether CH₃OCH₃ both have formula C₂H₆O. Explain why ethanol is expected to have the higher boiling point at the same pressure.',steps:[['Both have similar molar mass and both have dispersion forces. Both molecules are polar.','A fair comparison includes the interactions shared by the substances.'],['Ethanol has an O–H donor and oxygen lone pairs, so neighbouring ethanol molecules can hydrogen-bond.','The molecular structure supplies both a donor and an acceptor.'],['Dimethyl ether has oxygen lone pairs but no O–H bond, so pure ether cannot form the same donor–acceptor network.','An acceptor alone does not supply a hydrogen-bond donor.']],result:'Ethanol is expected to boil at the higher temperature because its molecules have additional hydrogen-bonding interactions.',meaning:'Dimethyl ether can still accept hydrogen bonds from water. The statement about the pure substance does not prohibit interactions in mixtures.'},
  {title:'Explain solubility without an absolute rule',problem:'Explain why water generally mixes more favourably with ethanol than with a non-polar hydrocarbon such as hexane.',steps:[['Water molecules form an extensive hydrogen-bond network.','Separating water molecules changes those interactions.'],['Ethanol’s OH group can form hydrogen bonds with water.','New solute–solvent interactions help compensate for the interactions disrupted on mixing.'],['Hexane cannot form hydrogen bonds with water, although dispersion forces still act between them.','The full energetic and entropic balance is less favourable for extensive mixing.']],result:'Polarity and hydrogen-bond compatibility help explain the difference; “like dissolves like” is a guide, not a complete law.',meaning:'Actual solubility depends on temperature and the free-energy balance; do not predict exact solubility from one interaction label.'},
  {title:'Vaporise a stated amount of liquid water',problem:'At its boiling temperature under the stated conditions, 0.250 mol of liquid water vaporises. Take ΔH_{vap} = 40.7 kJ/mol. Find the heat absorbed.',steps:[['The water is already at the phase-change temperature, so q = nΔH_{vap}.','No preliminary warming is included in this problem.'],['q = 0.250 mol × 40.7 kJ/mol = 10.175 kJ.','Moles cancel, leaving energy.'],['Report 10.2 kJ absorbed to three significant figures.','Vaporisation requires energy input.']],result:'q = +10.2 kJ for the water.',meaning:'H₂O molecules remain H₂O in the vapour. For condensation of the same amount under the same conditions, q has the opposite sign.'},
  {title:'Changing the pressure changes the boiling temperature',problem:'A liquid boils in a vessel. Explain what happens to its boiling temperature if the external pressure is lowered.',steps:[['At boiling, the liquid’s vapour pressure equals the external pressure.','This is the condition to compare.'],['A lower external pressure can be matched at a lower temperature on the same vapour-pressure curve.','Equilibrium vapour pressure increases with temperature along the liquid–vapour curve.']],result:'The boiling temperature falls when external pressure is reduced.',meaning:'This explains vacuum distillation. It does not mean that the substance’s covalent bonds have become weaker.'},
 ],
 mistakes:[['Boiling breaks each molecule into atoms.','Boiling a molecular liquid separates molecules; it normally preserves the covalent bonds within them.'],['Every substance containing H can hydrogen-bond to itself.','Check for an appropriate donor and acceptor; a C–H bond does not supply the usual introductory donor.'],['Dispersion acts only in non-polar molecules.','Dispersion is present in all atoms and molecules, alongside any other interactions.'],['A stronger named force always guarantees a higher boiling point.','Compare the whole molecules: size, polarisability, shape and all available interactions.']],
 sources:[{title:'OpenStax Chemistry 2e — Intermolecular forces',url:'https://openstax.org/books/chemistry-2e/pages/10-1-intermolecular-forces'},{title:'OpenStax Chemistry 2e — Phase transitions',url:'https://openstax.org/books/chemistry-2e/pages/10-3-phase-transitions'}],
 checks:[['vaporisation kJ',.250*40.7,10.175,1e-12],['condensation kJ',-.250*40.7,-10.175,1e-12],['C2H6O molar mass',2*12.01+6*1.008+16,46.068,1e-10]],
};
