import {svg, text, line, vector} from '../svg.mjs';
const current=1.5, waterSpeed=2.5, width=100;
const crossingSpeed=Math.sqrt(waterSpeed**2-current**2);
export default {
 id:'relative-motion', title:'Relative motion and reference frames',
 intro:'A speed is incomplete until you say what it is measured relative to. A person can walk towards the back of a moving train while still moving forwards relative to the platform. Naming the observer removes the apparent contradiction.',
 ideas:[
  'Write v_{A/B} for the velocity of object A measured by observer B. Keep one set of axis directions when combining velocities. In one dimension the signs carry direction; in two dimensions add the x-components and y-components separately. Speeds, which are magnitudes, cannot generally be added as scalars.',
  'Position vectors satisfy r_{A/C} = r_{A/B} + r_{B/C}: go from C to B, then from B to A. Differentiating with respect to the same time gives v_{A/C} = v_{A/B} + v_{B/C}. The middle observer B connects the two terms. This is the classical, nonrelativistic rule, valid for speeds far below the speed of light and axes that do not rotate relative to each other.',
  'For two objects observed from the ground G, v_{A/B} = v_{A/G} − v_{B/G}. Reversing the observer reverses the vector: v_{B/A} = −v_{A/B}. If the frames move at constant velocity relative to one another, their measured accelerations agree. An accelerating or rotating frame needs further care when applying Newton’s laws.',
  'For a river or wind problem, distinguish the vehicle’s velocity relative to the fluid from the fluid’s velocity relative to the ground. A boat’s heading is the direction it points through the water; its track is the path seen from the bank. They differ when a current has a sideways component.',
 ],
 symbols:[['v_{A/B}','velocity of A relative to B','m/s'],['u','boat speed relative to water','m/s'],['c','current speed relative to bank','m/s'],['w','river width, measured perpendicular to banks','m'],['α','upstream heading angle measured from straight across','° or rad']],
 formulas:[
  {name:'Add velocities through a named frame',f:'v_{A/C} = v_{A/B} + v_{B/C}',when:'Vectors expressed using consistent axes and the same time; classical speeds.'},
  {name:'Observe A from B',f:'v_{A/B} = v_{A/G} − v_{B/G}',when:'Both given velocities are measured from the same frame G.'},
  {name:'Point straight across a uniform river',f:'t = w/u;   downstream drift = ct',when:'The boat points perpendicular to the banks. Current is parallel to the banks; u and c are constant.'},
  {name:'Land directly opposite',f:'sin α = c/u;   v_{across} = √{u^{2} − c^{2}};   t = {{w|√{u^{2} − c^{2}}}}',when:'Aim upstream by α from straight across. A positive crossing speed requires u > c. At u = c, cancellation uses the whole boat speed and the boat cannot cross.'},
 ],
 figure:{svg:svg('support-relative',{w:500,h:260,title:'A current changes a boat’s velocity relative to the bank',desc:'East is right and north is up. From a common starting point the boat velocity relative to water is 2.5 metres per second north. A 1.5 metres per second eastward current is then added head to tail. The diagonal is the boat velocity relative to the bank. All three velocity arrows use the same scale.'},
  line(90,210,390,210,{color:'#d0ddd7'})+line(90,210,90,35,{color:'#d0ddd7'})
  +vector(110,205,110,65,'a',3)+vector(110,65,194,65,'b',3)+vector(110,205,194,65,'d',3)
  +text(32,132,'2.5 m/s',{size:14})+text(118,46,'current 1.5 m/s east',{size:14})
  +text(222,124,'bank velocity: 2.92 m/s',{size:14})+text(222,147,'heading and track differ',{size:14})
  +text(100,238,'North = across the river; east = downstream',{size:14})),caption:'Pointing north through the water produces a north-east track relative to the bank. The diagonal comes from vector addition, not 2.5 + 1.5.'},
 table:{caption:'Two headings for the same 100 m river',head:['Heading through water','Across speed','Time','Downstream drift'],rows:[['Straight across','2.5 m/s','40 s','60 m'],['36.9° upstream from across','2.0 m/s','50 s','0 m'],['Current as fast as boat; aim to cancel drift','0 m/s','No finite crossing time','No crossing']]},
 examples:[
  {title:'Walking backwards on a moving train',problem:'A train moves east at 12 m/s. A passenger walks west along it at 1.5 m/s relative to the train. Find the passenger’s velocity relative to the platform.',steps:[['Choose east positive. v_{P/T} = −1.5 m/s and v_{T/G} = +12 m/s.','The westward walking velocity must have the opposite sign.'],['v_{P/G} = −1.5 + 12 = +10.5 m/s.','The train frame cancels between the two terms.']],result:'The passenger moves east at 10.5 m/s relative to the platform.',meaning:'Walking towards the back of the train does not necessarily mean moving west over the ground.'},
  {title:'A faster vehicle approaches from behind',problem:'Car A is 180 m behind car B. Both move east at constant speeds: A at 24 m/s and B at 18 m/s. Find when A reaches B.',steps:[['v_{A/B} = 24 − 18 = 6 m/s east.','The gap closes at the relative speed, not at either ground speed.'],['t = 180/6 = 30 s.','Initial separation divided by constant closing speed.'],['A travels 24 × 30 = 720 m; B travels 18 × 30 = 540 m.','A covers 180 m more, exactly the initial gap.']],result:'A reaches B after 30 s.',meaning:'Adding 24 and 18 would apply to head-on motion, not to vehicles travelling in the same direction.'},
  {title:'Point straight across and accept the drift',problem:'A boat travels at 2.5 m/s relative to water, pointing straight across a 100 m river. The current is 1.5 m/s downstream. Find crossing time, drift and speed relative to the bank.',steps:[['Across component = 2.5 m/s; downstream component = 1.5 m/s.','The current changes only the downstream component in this model.'],['t = 100/2.5 = 40 s; drift = 1.5 × 40 = 60 m.','Use the across component to cross the width.'],['Ground speed = √{2.5^{2} + 1.5^{2}} = 2.92 m/s.','The perpendicular components form a right triangle.']],result:'40 s, landing 60 m downstream; speed relative to the bank ≈ 2.92 m/s.',meaning:'Dividing 100 m by 2.92 m/s would mix a perpendicular width with speed along a diagonal path.'},
  {title:'Aim upstream to land directly opposite',problem:'Use the same river and boat. Find the upstream heading and crossing time for zero downstream drift.',steps:[['Choose the boat’s upstream component to be −1.5 m/s.','It must cancel the water’s +1.5 m/s downstream velocity.'],['sin α = 1.5/2.5 = 0.60, so α = 36.9° upstream from straight across.','The total velocity through water remains 2.5 m/s.'],['Across component = √{2.5^{2} − 1.5^{2}} = 2.0 m/s; t = 100/2.0 = 50 s.','Part of the boat’s velocity is now used to cancel the current.']],result:'Aim 36.9° upstream from straight across; crossing takes 50 s.',meaning:'Zero drift takes longer than simply pointing straight across. If the current is at least the boat’s water speed, a direct opposite-bank crossing is impossible in this model.'},
 ],
 mistakes:[['Adding speeds without directions.','Add signed components of velocities. Then calculate a magnitude if needed.'],['Using diagonal ground speed to cross a perpendicular river width.','Time uses the velocity component in the direction of that width.'],['Using the same velocity for every observer.','Write both the moving object and the reference frame on each velocity.']],
 sources:[{title:'OpenStax University Physics 1 — Relative motion',url:'https://openstax.org/books/university-physics-volume-1/pages/4-5-relative-motion-in-one-and-two-dimensions'}],
 checks:[['train passenger',12-1.5,10.5,0],['catch time',180/(24-18),30,0],['catch distance',24*30-18*30,180,0],['river time',width/waterSpeed,40,0],['river drift',current*width/waterSpeed,60,0],['ground speed',Math.hypot(current,waterSpeed),2.91548,.00001],['upstream angle',Math.asin(current/waterSpeed)*180/Math.PI,36.8699,.0001],['across speed',crossingSpeed,2,0],['direct crossing time',width/crossingSpeed,50,0]],
};
