// Course identifiers and placement follow the supplied plan image and the saved
// 2023 college study plan. Learning topics below are editorial study suggestions.
const rows = [
 [1,'MA101','Calculus I',4,'math','Limits and continuity|Derivatives and rates|Optimisation and curve shape'],
 [1,'PHY101','General Physics I',4,'physics','Units and vectors|Motion and forces|Energy and momentum'],
 [1,'CHEM101','General Chemistry I',4,'chemistry','Atoms and bonds|Amounts and solutions|Energy and electrochemistry'],
 [1,'ESP101','Introduction to Academic Discourse',3,'communication','Read a scientific paragraph|Build an evidence-based paragraph|Summarise and cite a source'],
 [1,'ARB101','Practical Grammar',2,'communication','Sentence structure|Grammatical agreement|Edit for clear meaning'],
 [1,'HPE101','Health and Physical Education',1,'general','Course expectations|Supervised practical activities|Reflect on participation'],
 [2,'ARB102','Objective Writing',2,'communication','Separate evidence from opinion|Structure a report|Revise a scientific summary'],
 [2,'CSE101','Introduction to Programming',2,'computing','Variables and expressions|Conditions and loops|Functions and files'],
 [2,'ESP102','Introduction to Report Writing',3,'communication','Define audience and purpose|Explain a graph|Write methods and findings'],
 [2,'ISL101','Belief and Its Consequences',2,'general','Read assigned source texts|Define key concepts|Explain connections with evidence'],
 [2,'MA102','Calculus II',4,'math','Integration and accumulation|Integration techniques|Sequences and series'],
 [2,'PHY102','General Physics II',4,'physics','Waves and sound|Thermal processes|Electricity and magnetism'],
 [3,'CE201','Principles of Chemical Engineering',3,'process','Units and process variables|Nonreacting material balances|Reacting balances and energy'],
 [3,'CHEM211','General Chemistry II',3,'chemistry','Equilibrium and acids|Reaction kinetics|Spontaneity and modern materials'],
 [3,'CHEM212','General Chemistry II Lab',1,'lab','Prepare from the approved method|Record observations and units|Evaluate uncertainty and results'],
 [3,'ESP201','Academic and Professional Communication',3,'communication','Present an engineering argument|Write a professional message|Document a team decision'],
 [3,'ISL201','Professional Ethics',2,'general','Identify an ethical issue|Compare responsibilities|Justify a professional decision'],
 [3,'MA201','Calculus III',3,'math','Vectors and three-dimensional coordinates|Partial derivatives|Multiple integrals'],
 [3,'MA202','Probability and Statistics for Engineers',3,'math','Describe variation|Probability and distributions|Estimation and hypothesis tests'],
 [4,'CE203','Introduction to Chemical Engineering Computing',1,'computing','Translate balances into equations|Solve and check a model|Interpret numerical results'],
 [4,'CE207','Organic Chemistry Lab',1,'lab','Understand the approved procedure|Record qualitative and quantitative evidence|Explain observations'],
 [4,'CE202','Materials Science',3,'chemistry','Structure and properties|Material behaviour|Selection for a stated service'],
 [4,'CE204','Introduction to Chemical Engineering Computing Lab',1,'computing','Implement a small model|Test units and boundary cases|Report reproducible results'],
 [4,'CE205','Fluid Mechanics',3,'process','Pressure and fluid properties|Continuity and energy|Pipe flow and losses'],
 [4,'CE206','Organic Chemistry',3,'chemistry','Structure and functional groups|Reaction patterns|Characterisation and evidence'],
 [4,'CSE201','Introduction to Data Science',3,'computing','Prepare and inspect data|Fit and evaluate a model|Separate training from evaluation'],
 [4,'MA203','Elements of Differential Equations',3,'math','First-order equations|Linear higher-order equations|Initial conditions and interpretation'],
 [5,'ARB201','Literary Styles',2,'communication','Read for structure and style|Support an interpretation|Write for audience and purpose'],
 [5,'CE301','Chemical Engineering Thermodynamics',3,'process','Systems and state properties|First and second laws|Equilibrium and property models'],
 [5,'CE302','Heat Transfer',3,'process','Conduction|Convection and resistance|Heat exchanger balances'],
 [5,'CE303','Mass Transfer',3,'process','Diffusion and concentration gradients|Interphase transfer|Mass transfer balances'],
 [5,'CSE301','Introduction to Artificial Intelligence',3,'computing','Search and representation|Learning from data|Evaluate uncertainty and failure'],
 [5,'MA301','Numerical Methods for Engineers',3,'math','Roots and linear systems|Interpolation and numerical derivatives|Numerical differential equations'],
 [6,'CE300','Design Project I',2,'design','Define a justified problem|Compare feasible concepts|Document assumptions and a project plan'],
 [6,'CE304','Separation Processes',3,'process','Phase equilibrium|Flash and column distillation|Absorption and extraction'],
 [6,'CE305','Kinetics and Reactor Design',3,'process','Rate laws and conversion|Batch and flow reactor balances|Interpret design assumptions'],
 [6,'CE306','Chemical Engineering Lab I',2,'lab','Prepare an experimental balance|Record transport measurements|Compare model and evidence'],
 [6,'CE307','Physical Chemistry',3,'chemistry','Solutions and equilibrium|Kinetics|Electrochemical systems'],
 [6,'CE308','Physical Chemistry Lab',1,'lab','Connect an approved experiment to theory|Record and process measurements|Explain uncertainty'],
 [6,'ISL301','Human Right in Islam',2,'general','Define course concepts|Read assigned evidence|Discuss applications with sources'],
 [6,'MS301','Business and Entrepreneurship',2,'design','Define a customer need|Evaluate costs and value|Build a supported business proposal'],
 [7,'CE400','Design Project II',2,'design','Develop the selected design|Check calculations and constraints|Present a defensible final report'],
 [7,'CE401','Process Dynamics and Control',3,'process','Dynamic balances|Response to disturbances|Feedback and stability'],
 [7,'CE402','Plant Design and Economics',3,'design','Flowsheets and equipment sizing|Capital and operating costs|Compare alternatives and uncertainty'],
 [7,'CE403','Chemical Engineering Lab II',2,'lab','Plan from the approved lab brief|Analyse separation and reaction data|Defend conclusions'],
 [8,'CE490','Internship',6,'design','Agree learning objectives with a supervisor|Maintain a nonconfidential learning record|Reflect on engineering practice'],
 ['elective','CE404','Polymer Technology',3,'process','Polymer structure|Polymerisation concepts|Processing and material properties'],
 ['elective','CE405','Desalination',3,'process','Water and salt balances|Thermal and membrane separation|Energy and performance measures'],
 ['elective','CE406','Corrosion',3,'chemistry','Electrochemical driving forces|Corrosion mechanisms|Protection and material selection'],
 ['elective','CE407','Process Pollution Control',3,'process','Pollutant sources and balances|Treatment principles|Interpret environmental performance'],
];
const existing = {MA101:'/semester-1/math/',PHY101:'/semester-1/physics/',CHEM101:'/semester-1/chemistry/'};
export const catalog = {
 schemaVersion:1, id:'yanbu-bsce', version:'2026-09-19',
 sources:[
  {id:'student-plan',label:'Study plan image supplied by the project owner, 19 September 2026',scope:'Semester 2–8 course placement and four elective options; Semester 1 is outside the crop.'},
  {id:'college-plan-2023',label:'Saved college study plan, 21 June 2023',url:'https://www.rcjy.edu.sa/umb/rcjy-media/vhvh5a22/bachelor-of-science-in-chemical-engineering-21-6-2023.pdf',scope:'Semester 1, credits and two elective slots in Semester 7. Current applicability requires confirmation.'},
  {id:'college-descriptions',label:'Saved college course descriptions',url:'https://www.rcjy.edu.sa/umb/rcjy-media/jq1nholw/bscecourse-descriptions.pdf',scope:'Broad topic reference. Several course codes differ from the study plan; plan codes are used.'}
 ],
 discrepancies:[
  'The description document labels Academic Discourse ESP 401, Principles of Chemical Engineering CL 201, Differential Equations MA 205, and Physical Chemistry CPE 307. This map uses ESP 101, CE 201, MA 203 and CE 307 from the study plan.',
  'The supplied image shows remaining courses, not the whole first semester. Semester 1 is restored from the saved college plan.',
  'The 2023 plan assigns two 3-credit electives to Semester 7. The four displayed electives are options, not four compulsory courses.',
  'Prerequisites, registration eligibility and current course changes must be checked with the college. Suggested preparation here is a learning aid.'
 ],
 semesters:[18,17,18,18,17,18,16,6].map((credits,i)=>({number:i+1,credits,electiveCredits:i===6?6:0})),
 courses:rows.map(([semester,id,title,credits,area,topics])=>({
  id,code:id.replace(/(\d)/,' $1'),title,semester,credits,area,
  sourceIds:semester===1?['college-plan-2023']:['student-plan','college-plan-2023'],
  scopeStatus:'proposed-study-sequence', topics:topics.split('|'),
  preparation: area==='math'?['algebra','trigonometry']:['process','physics','chemistry','computing'].includes(area)?['basic-math','algebra']:[],
  resources: existing[id]?[{kind:'lesson-collection',label:'Open current course lessons',href:existing[id]}]:id==='CE201'?[{kind:'starter-lesson',label:'Read the first material balance lesson',href:'/program/lessons/material-balances/'}]:[],
  status:existing[id]?'lessons-available':id==='CE201'?'starter-available':'outline-only',
  lessons:existing[id]?[]:id==='CE201'?['material-balances']:[],
  officialPrerequisites:null,
 }))
};
