/** The student entrance is Semester 1. This builder owns the three subject hubs,
 * nine reading collections and 26 combined explanations. Original lesson data
 * stays separate from presentation; there is no assessment or progress runtime.
 * tools/data/study-library.json preserves all 333 published source lesson units.
 */
import fs from 'node:fs';
import path from 'node:path';
import {lessons} from '../bayt/data/lessons/index.mjs';
import {validate} from '../bayt/data/lessons/schema.mjs';
const root=path.resolve(import.meta.dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const library=JSON.parse(read('tools/data/study-library.json'));
const curriculum=JSON.parse(read('semester-1/curriculum.json'));
const H=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const prose=s=>H(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const write=(p,s)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),s+'\n');};
const meta={ma101:{name:'Mathematics',glyph:'∫',summary:'Functions, limits, derivatives and their applications.',color:'math'},phy101:{name:'Physics',glyph:'F = ma',summary:'Measurement, motion, forces, energy and physical models.',color:'physics'},chemistry:{name:'Chemistry',glyph:'H₂O',summary:'Atoms, bonding, reactions, solutions and chemical energy.',color:'chemistry'}};
const engines={book:{name:'Book',title:'Reference & formulas',description:'Build the idea from its definition. Read the governing relations, conditions and worked reasoning.'},pearson:{name:'Pearson',title:'Methods & worked examples',description:'See how to select a method, organize the given information and carry a calculation through.'},educator:{name:'Educator',title:'Concepts & explanations',description:'Follow the physical meaning, visual explanations and the reasoning behind each step.'}};
const courses=curriculum.courses.map(c=>({...c,...meta[c.id]}));
const count=(id,r)=>library[id][r].units.reduce((n,u)=>n+u.lessons.length,0);
const total=id=>Object.keys(engines).reduce((n,r)=>n+count(id,r),0);
const subject=c=>`/semester-1/${c.path}/`;
const routeUrl=(c,r)=>`/${c.id}/${r}/`;
function header(c){return `<a class="skip" href="#content">Skip to content</a><header class="site-header"><a class="brand" href="/">BAYT AL-FUAD<span>Semester 1 · Study library</span></a><nav aria-label="Subjects">${courses.map(x=>`<a href="${subject(x)}"${c?.id===x.id?' aria-current="page"':''}>${x.name}</a>`).join('')}</nav></header>`;}
function shell(title,body,c,wide=false){return `<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Semester 1 study material: Mathematics, Physics and Chemistry. Explanations, formulas, diagrams and fully worked examples."><title>${H(title)} | Bayt Al-Fuad</title><link rel="stylesheet" href="/semester-1/assets/study.css"></head><body class="${c?.color??'home'}">${header(c)}<main id="content" class="${wide?'reader':'page'}">${body}</main><footer class="site-footer"><a href="/">Semester 1</a><span>Understand the idea. Follow the formula. Read the worked example.</span></footer></body></html>`;}
function breadcrumbs(c,label=''){return `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Semester 1</a>${c?`<span>/</span>${label?`<a href="${subject(c)}">${c.name}</a><span>/</span><span>${H(label)}</span>`:`<span>${c.name}</span>`}`:''}</nav>`;}
function engineCards(c){return `<div class="engine-grid">${Object.entries(engines).map(([r,e],i)=>`<a class="engine-card" href="${routeUrl(c,r)}"><div class="engine-meta"><span>0${i+1} / STUDY ROUTE</span><span>${count(c.id,r)} lessons</span></div><h3>${e.name}<span aria-hidden="true">↗</span></h3><strong>${e.title}</strong><p>${e.description}</p><span class="text-link">Read ${e.name} →</span></a>`).join('')}</div>`;}
const home=`<section class="home-hero"><div><p class="eyebrow">MATHEMATICS · PHYSICS · CHEMISTRY</p><h1>Semester 1.</h1><p class="lead">Choose a subject. Open Book, Pearson or Educator.<br>Read the explanation, the formula and the worked example.</p></div><aside class="hero-note"><span class="eyebrow">THE STUDY LIBRARY</span><strong>3 subjects<span>9 reading collections</span></strong><p>All the material is open to read.<br>Start wherever you need an explanation.</p></aside></section><section aria-labelledby="subjects-title"><div class="section-heading"><h2 id="subjects-title">Choose your subject</h2><p>Mathematics · Physics · Chemistry</p></div><div class="subject-grid">${courses.map(c=>`<article class="subject-card ${c.color}" data-subject="${c.id}"><div class="subject-art" aria-hidden="true">${c.glyph}</div><div class="subject-body"><p class="eyebrow">${c.code}</p><h2><a href="${subject(c)}">${c.name}</a></h2><p>${c.summary}</p><a class="button" href="${subject(c)}">Open ${c.name} →</a><nav class="direct-routes" aria-label="${c.name} reading routes">${Object.entries(engines).map(([r,e])=>`<a href="${routeUrl(c,r)}">${e.name}</a>`).join('')}</nav><p class="collection-count">${total(c.id)} lesson units across the three routes</p></div></article>`).join('')}</div></section><p class="home-footnote">Three ways to understand the same subject. Choose the style that helps, or compare explanations.</p>`;
// Preserve old bookmarks as useful entrances, rather than leaving a second dashboard.
for(const p of ['index.html','bayt/index.html','semester-1/index.html'])write(p,shell('Semester 1 · Mathematics, Physics & Chemistry',home));

function table(t){return `<div class="table-wrap" tabindex="0" role="region" aria-label="${H(t.caption)}"><table><caption>${H(t.caption)}</caption><thead><tr>${t.head.map(x=>`<th scope="col">${H(x)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(row=>`<tr>${row.map((x,i)=>i?`<td>${H(x)}</td>`:`<th scope="row">${H(x)}</th>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function steps(items){return `<ol class="worked-steps">${items.map(s=>`<li><p>${prose(s.do)}</p><p class="reason">${prose(s.why)}</p></li>`).join('')}</ol>`;}
function section(id,title,body){return `<section id="${id}" class="reading-section"><h2>${title}</h2>${body}</section>`;}
function topicContent(l,t){
 const d=l.reference.derivation;
 return section('overview','The idea',`<p class="large-text">${H(t.idea)}</p><div class="worked-application"><h3>A first example</h3><p>${H(t.example)}</p></div><p><strong>Engineering connection.</strong> ${H(t.context)}</p><h3>What this explanation develops</h3><ul>${l.objectives.map(x=>`<li>${H(x)}</li>`).join('')}</ul>`)
 +section('definitions','Definitions & meaning',(l.reference.explanations??[]).map(x=>`<p>${prose(x)}</p>`).join('')+`<dl class="definitions">${l.reference.definitions.map(x=>`<div><dt>${H(x.en)}</dt><dd>${prose(x.text)}</dd></div>`).join('')}</dl>`)
 +section('formulas','Formulas & conditions',`<div class="formula-list">${(l.reference.relations??[]).map(x=>`<article><h3>${H(x.name)}</h3><p class="formula">${H(x.formula)}</p><p>${prose(x.note)}</p></article>`).join('')}</div>`+(d?`<h3>${H(d.title)}</h3><p>${H(d.intro)}</p>${steps(d.steps)}`:''))
 +section('visual','See the concept',`<h3>${H(l.visual.title)}</h3><figure class="concept-figure">${l.visual.figure.svg}<figcaption>${H(l.visual.figure.caption)}</figcaption></figure><p class="image-description">${H(l.visual.figure.alt)}</p>${table(l.visual.table)}<p>${prose(l.visual.reading??'')}</p>`)
 +section('worked','Worked examples',`<p>${H(l.guided.start)}</p>${l.guided.workedExamples.map(w=>`<article class="worked-example"><h3>${H(w.title)}</h3><p>${H(w.task)}</p>${steps(w.steps)}<p class="result"><strong>Result:</strong> ${H(w.answer)}</p></article>`).join('')}`)
 +section('applications','Further worked applications',l.questionTypes.map(q=>`<article class="worked-example" data-worked-example="${H(q.id)}"><h3>${H(q.family)}</h3><p class="muted">${H(q.aim)}</p><p>${H(q.prompt)}</p><div class="worked-solution"><p>${H(q.solution)}</p><p><strong>Result:</strong> ${H(q.answer)} ${H(q.unit)}</p></div></article>`).join(''))
 +section('clarifications','Details that matter',(l.guided.skipped??[]).map(s=>`<p class="clarification">${H(s.a)}</p>`).join('')+`<h3>Useful background</h3>${l.prerequisites.map(p=>`<article><h4>${H(p.title)}</h4><p>${H(p.recap)}</p></article>`).join('')}`)
 +`<details class="scope-note"><summary>Scope of this explanation</summary><ul>${l.boundaries.map(b=>`<li>${H(b)}</li>`).join('')}</ul></details>`;
}
function routeTabs(c,active){return `<nav class="route-tabs" aria-label="Study routes"><a href="${subject(c)}">${c.name}</a>${Object.entries(engines).map(([r,e])=>`<a href="${routeUrl(c,r)}"${r===active?' aria-current="page"':''}>${e.name}</a>`).join('')}</nav>`;}
for(const c of courses){
 const rows=c.topics.map((t,i)=>`<a class="topic-row" href="${t.href}"><span>${String(i+1).padStart(2,'0')}</span><div><h3>${H(t.title)}</h3><p>${H(t.outcome)}</p></div><span aria-hidden="true">→</span></a>`).join('');
 const hub=`${breadcrumbs(c)}<section class="subject-heading"><div><p class="eyebrow">SEMESTER 1 · ${c.code}</p><h1>${c.name}</h1><p class="lead">${H(c.scope)}</p></div><div class="subject-symbol" aria-hidden="true">${c.glyph}</div></section><section aria-labelledby="routes-title"><div class="section-heading"><div><p class="eyebrow">THE THREE STUDY ROUTES</p><h2 id="routes-title">Book. Pearson. Educator.</h2></div><p>Every collection opens directly to its material.</p></div>${engineCards(c)}<p class="collection-note">These are original study explanations organized around the three routes. Publisher videos are supplementary and may require an external account.</p></section><section class="topic-section" aria-labelledby="topics-title"><div class="section-heading"><div><p class="eyebrow">READ BY SEMESTER TOPIC</p><h2 id="topics-title">Explanations, formulas & worked examples</h2></div><p>${c.topics.length} combined topic guides</p></div><div class="topic-list">${rows}</div></section><p class="scope-footer">The reading collections include supporting and extension chapters. Use your lecturer’s current outline to confirm assessed topics and their order.</p>`;
 write(`semester-1/${c.path}/index.html`,shell(c.name,hub,c));
 write(`${c.id}/index.html`,shell(c.name,hub,c));
 for(const [r,e] of Object.entries(engines)){
  const data=library[c.id][r];
  const toc=data.units.map(u=>`<div class="toc-group"><a class="toc-unit" href="#${u.id}">${H(u.title)}</a>${u.lessons.map(l=>`<a href="#${l.id}">${H(l.title)}</a>`).join('')}</div>`).join('')+`<a class="toc-unit" href="#equation-review">Formula reference</a>`;
  const material=data.units.map(u=>`<section id="${u.id}" class="library-unit"><p class="eyebrow">${H(e.name)} · ${c.name}</p><h2>${H(u.title)}</h2>${u.lessons.map(l=>l.html).join('')}</section>`).join('')+data.formulaReview;
  const body=`<div class="reader-top">${breadcrumbs(c,e.name)}${routeTabs(c,r)}</div><div class="reader-layout"><aside class="contents"><details open><summary>Contents · ${count(c.id,r)} lessons</summary><nav aria-label="Collection contents">${toc}</nav></details></aside><article class="reading-body"><header class="reading-heading"><p class="eyebrow">${c.code} · ${e.name.toUpperCase()} COLLECTION</p><h1>${c.name}: ${e.name}</h1><p class="lead">${e.title}</p><p>${e.description}</p><p class="reading-note">Read the lessons in sequence or choose one from the contents. Formulas and worked solutions are shown with each explanation.</p></header>${material}${data.credit}<p class="scope-footer">This collection includes supporting and extension material. Follow your lecturer’s current outline for assessed scope. ${r==='book'?'':'This is an independent study companion, not a reproduction of the publisher’s full course.'}</p><a class="button" href="${subject(c)}">Back to ${c.name} →</a></article></div>`;
  write(`${c.id}/${r}/index.html`,shell(`${c.name} · ${e.name}`,body,c,true));
 }
 for(const t of c.topics){
  const l=lessons.find(x=>x.course===c.id&&x.topic===t.id);
  if(!l||validate(l).length)throw new Error(`Invalid teaching data: ${c.id}.${t.id}`);
  const anchors=[['overview','The idea'],['definitions','Definitions & meaning'],['formulas','Formulas & conditions'],['visual','See the concept'],['worked','Worked examples'],['applications','Further applications'],['clarifications','Details that matter']];
  const mapped=Object.entries(engines).map(([r,e])=>`<a href="${routeUrl(c,r)}#${t.resources[r]?.[0]??'lesson-01'}">${e.name} →</a>`).join('');
  const body=`<div class="reader-top">${breadcrumbs(c,t.title)}${routeTabs(c)}</div><div class="reader-layout"><aside class="contents"><details open><summary>In this explanation</summary><nav aria-label="Lesson contents">${anchors.map(([id,title])=>`<a href="#${id}">${title}</a>`).join('')}<div class="toc-group"><span class="eyebrow">THIS TOPIC IN EACH ROUTE</span>${mapped}</div><div class="toc-group"><span class="eyebrow">${c.name.toUpperCase()} TOPICS</span>${c.topics.map(x=>`<a href="${x.href}"${x.id===t.id?' aria-current="page"':''}>${H(x.title)}</a>`).join('')}</div></nav></details></aside><article class="reading-body"><header class="reading-heading"><p class="eyebrow">${c.code} · TOPIC ${String(t.sequence).padStart(2,'0')}</p><h1>${H(t.title)}</h1><p class="lead">${H(t.outcome)}</p><nav class="inline-routes" aria-label="Read this topic in a study route">${mapped}</nav></header>${topicContent(l,t)}<nav class="next-topic" aria-label="Next reading">${c.topics[t.sequence]?`<a class="button" href="${c.topics[t.sequence].href}">Next: ${H(c.topics[t.sequence].title)} →</a>`:''}<a href="${subject(c)}">All ${c.name} topics</a></nav></article></div>`;
  write(`${t.href.slice(1)}index.html`,shell(`${t.title} · ${c.name}`,body,c,true));
 }
}
console.log('Built focused Semester 1: 3 subjects, 9 reading collections, 333 source units and 26 topic guides. No assessment UI or runtime.');
