"""Published YIC scope plus explicitly provisional teaching sequences.
Existing lessons remain source-specific. These records select bounded resources.
"""

PLAN = 'https://www.rcjy.edu.sa/umb/rcjy-media/vhvh5a22/bachelor-of-science-in-chemical-engineering-21-6-2023.pdf'
DESCRIPTION = 'https://www.rcjy.edu.sa/umb/rcjy-media/jq1nholw/bscecourse-descriptions.pdf'

def q(prompt, answer, why, unit='', tolerance=0.0001):
    return dict(prompt=prompt, answer=answer, explanation=why, unit=unit, tolerance=tolerance)

def topic(id, title, outcome, idea, example, context, foundation, source, diagnostic, transfer):
    return dict(id=id,title=title,outcome=outcome,idea=idea,example=example,context=context,
                foundation=foundation,resources={k:[f'lesson-{n:02d}' for n in ns] for k,ns in source.items()},
                diagnostic=diagnostic,transfer=transfer)

MATH = [
topic('limits','Limits','Find a limit before substituting into a broken expression.',
'A limit describes nearby behaviour. A missing value at the point does not by itself prevent a limit. Factor or rationalise an indeterminate expression, cancel only for nearby allowed inputs, and then evaluate.',
'For (x² − 9)/(x − 3), factor the numerator. For x ≠ 3 the expression is x + 3, so its limit as x approaches 3 is 6. The original expression is still undefined at 3.',
'A limiting model describes what a process approaches, even when an ideal endpoint is not directly measured.', 'algebra',
{'educator':[4,5],'pearson':[7,8],'book':[7,8]},
q('Find the limit of (x² − 4)/(x − 2) as x approaches 2.',4,'For x ≠ 2, the expression simplifies to x + 2.'),
q('Find the limit of (x² − 25)/(x − 5) as x approaches 5.',10,'Factor as (x − 5)(x + 5), cancel away from 5, then evaluate x + 5.')),
topic('continuity','Continuity','Distinguish a function value from its limit.',
'Continuity at a point requires a defined value, an existing two-sided limit, and equality between them. The Intermediate Value Theorem needs continuity on the whole closed interval.',
'If f(x) = (x² − 9)/(x − 3) away from 3, defining f(3) = 6 fills the removable gap. Giving it any other value leaves a discontinuity.',
'Before treating a measured trend as smooth, identify whether a model has a genuine jump or just a missing observation.', 'graphs',
{'educator':[7],'pearson':[8],'book':[9]},
q('For f(x)=2x+1 when x≠2, what value of f(2) makes f continuous?',5,'The limit at 2 is 2(2)+1=5.'),
q('For f(x)=x²+2 when x≠3, what value of f(3) makes f continuous?',11,'The nearby polynomial tends to 3²+2=11.')),
topic('derivative','Derivative as a rate','Connect a tangent slope to an instantaneous rate.',
'The derivative is the limit of a difference quotient: [f(x+h) − f(x)]/h as h tends to zero. Average change uses two distinct points; instantaneous change uses their limiting slope. Keep the output unit divided by the input unit.',
'For f(x)=x², the difference quotient becomes 2x+h. Its limit is 2x. At x=3 the slope is 6.',
'If concentration is measured in mol/L and time in minutes, its derivative has units mol/(L·min).', 'graphs',
{'educator':[8,12],'pearson':[9,10],'book':[11,12]},
q('For f(x)=x², calculate f′(4).',8,'f′(x)=2x, so f′(4)=8.'),
q('A model C(t)=t²+3t gives concentration in mmol/L and time in min. Find C′(2).',7,'C′(t)=2t+3; at t=2 the rate is 7.','mmol/(L·min)')),
topic('rules','Differentiation rules','Choose a rule from the structure of the function.',
'Use the sum rule for sums, the product rule for products, the quotient rule for ratios, and the chain rule for composition. Differentiate the outer function, retain its input, then multiply by the derivative of that input. Trigonometric derivative rules assume radians.',
'For y=(3x+1)², the chain rule gives y′=2(3x+1)·3. At x=1, y′=24.',
'Rate models often combine an exponential trend with another changing quantity; identify structure before manipulating symbols.', 'algebra',
{'educator':[9,10,11,13,14,19],'pearson':[11,12,13,20],'book':[13,15,16,19]},
q('For y=(2x+1)², find y′ at x=1.',12,'y′=4(2x+1); at x=1 this is 12.'),
q('For y=x(x²+1), find y′ at x=2.',13,'Using the product rule, y′=(x²+1)+2x²=3x²+1.')),
topic('related-rates','Related rates','Differentiate a relation before inserting the current values.',
'First write a relation among the changing quantities. Differentiate with respect to time, including every chain-rule factor. Only then insert the quantities and rates at the specified instant.',
'For a square with side s, A=s² gives dA/dt=2s·ds/dt. At s=3 m and ds/dt=0.2 m/min, dA/dt=1.2 m²/min.',
'Tank level and stored volume are related by geometry. A level rate is not the same quantity as a volumetric flow rate.', 'algebra',
{'educator':[17,21],'pearson':[15],'book':[18,20]},
q('A square has side 4 m growing at 0.5 m/min. Find its area growth rate.',4,'dA/dt=2s·ds/dt=2·4·0.5.','m²/min'),
q('A cylindrical tank has fixed cross-sectional area 3 m². The level rises at 0.2 m/min. Find dV/dt.',0.6,'V=3h, hence dV/dt=3·0.2.','m³/min')),
topic('approximation','Linear approximation','Use a nearby tangent model and recognise its limits.',
'Near x=a, approximate f(x) by f(a)+f′(a)(x−a). This local model is useful when a small change is easier to handle than a full recalculation. A large change may produce a poor approximation.',
'Near x=4, √x≈2+(x−4)/4. At 4.04, the linear estimate is 2.01.',
'A sensitivity estimate describes the effect of a small input change; it is not a complete uncertainty analysis.', 'algebra',
{'educator':[22],'pearson':[16],'book':[21]},
q('Use the linearisation of √x at 4 to estimate √4.08.',2.02,'L(x)=2+(x−4)/4, so L(4.08)=2.02.'),
q('Use the linearisation of x² at x=3 to estimate (3.02)².',9.12,'L(x)=9+6(x−3); L(3.02)=9.12.')),
topic('mean-value','Rolle and Mean Value Theorems','Check conditions before claiming an interior derivative value.',
'The Mean Value Theorem needs continuity on [a,b] and differentiability on (a,b). It guarantees some interior c with f′(c)=[f(b)−f(a)]/(b−a). Rolle’s theorem adds equal endpoint values and guarantees f′(c)=0.',
'For f(x)=x² on [1,3], average slope is (9−1)/2=4. Since f′(x)=2x, c=2 satisfies the conclusion.',
'An average rate can guarantee an instantaneous matching rate only when the mathematical conditions hold.', 'graphs',
{'educator':[24],'book':[23]},
q('For f(x)=x² on [0,4], find the c guaranteed by the Mean Value Theorem.',2,'Average slope is 4, so 2c=4.'),
q('For f(x)=(x−2)² on [0,4], find the c satisfying Rolle’s conclusion.',2,'Endpoint values are both 4. f′(c)=2(c−2)=0 gives c=2.')),
topic('curve-shape','Extrema and curve shape','Use derivative signs and endpoints to justify a conclusion.',
'A critical point is a candidate, not automatically an extremum. Use the sign of f′ to identify increasing and decreasing intervals, f″ for concavity, and include interval endpoints when comparing absolute extrema.',
'For f(x)=x²−4x on [0,3], the critical point is x=2. Compare f(0)=0, f(2)=−4 and f(3)=−3. The minimum is −4.',
'A turning point in a cost model must lie inside the allowed operating range before it can be considered.', 'graphs',
{'educator':[23,25,27],'pearson':[17,18],'book':[22,24,25]},
q('Find the x-coordinate of the minimum of f(x)=x²−6x.',3,'f′=2x−6=0 gives x=3; f″=2>0.'),
q('Find the absolute maximum value of f(x)=x² on [−1,2].',4,'Compare the critical point x=0 and both endpoints: 0, 1 and 4.')),
topic('optimization','Optimization','Build a feasible one-variable model before differentiating.',
'Name the quantity to optimise and the constraint. Use the constraint to reduce the objective to one variable. Identify the allowed domain, find candidates, and justify the winning value by endpoints or derivative signs.',
'A rectangle with perimeter 20 m has area A=x(10−x). The derivative 10−2x vanishes at x=5, giving the maximum area 25 m².',
'A design optimum is meaningful only for the model and constraints used. Real equipment requires further engineering checks.', 'algebra',
{'educator':[28],'pearson':[19],'book':[26]},
q('A rectangle has perimeter 24 m. What side length gives the largest area?',6,'The maximum occurs for a square; 4s=24.','m'),
q('For a rectangle with perimeter 40 m, find the maximum area.',100,'A=x(20−x) is maximised at x=10; the area is 100.','m²')),
]

PHYSICS = [
topic('measurement','Units and measurement','Check units, scale and meaningful precision.',
'A physical equation must have compatible dimensions on both sides. Convert by multiplying ratios equal to one. A measurement has finite precision; retain guard digits during calculation and round the final result appropriately.',
'A speed of 72 km/h equals 72×1000/3600=20 m/s. Distance divided by time has dimensions of speed.',
'A unit mismatch in a process calculation can overwhelm an otherwise correct model.', 'units',
{'educator':[1],'pearson':[1,2],'book':[1]},
q('Convert 36 km/h to m/s.',10,'Multiply by 1000/3600.','m/s'),
q('A sample mass is 250 g and its volume is 100 cm³. Find its density.',2.5,'Density = mass/volume = 250/100.','g/cm³')),
topic('motion','Vectors and motion','Read direction and motion graphs before choosing an equation.',
'Velocity has direction; speed does not. Position-time slope is velocity, and velocity-time slope is acceleration. Constant-acceleration equations apply only over intervals where that assumption is justified.',
'Starting from rest with constant acceleration 2 m/s² for 3 s gives v=6 m/s and displacement 9 m.',
'A conveyor or moving sample can be described by position, velocity and acceleration without confusing the quantities.', 'graphs',
{'educator':[2,3,4,5],'pearson':[3,5,6,8],'book':[2,3,4,5]},
q('An object starts from rest and accelerates at 3 m/s² for 4 s. Find its final speed.',12,'v=u+at=0+3·4.','m/s'),
q('An object starts at 2 m/s and accelerates constantly at 2 m/s² for 3 s. Find displacement.',15,'s=ut+at²/2=6+9.','m')),
topic('forces','Newton laws and force diagrams','Define the object and sum external forces on it.',
'Draw all actual external forces on the chosen object. Choose axes and write a signed force balance. The net force equals mass times acceleration; motion alone does not imply a net force.',
'A 5 kg object with a net horizontal force of 15 N accelerates at 3 m/s². Weight and normal force may cancel vertically without cancelling horizontal force.',
'A diagram keeps drive, support and resistance forces distinct when modelling moving equipment.', 'trigonometry',
{'educator':[6,8],'pearson':[10,11,12,14],'book':[7]},
q('A net force of 12 N acts on a 3 kg object. Find its acceleration.',4,'a=Fnet/m=12/3.','m/s²'),
q('A 4 kg object has horizontal forces of 20 N right and 8 N left. Find acceleration, with right positive.',3,'Fnet=20−8=12 N; a=12/4.','m/s²')),
topic('friction','Friction and inclined surfaces','Choose the friction model and resolve forces.',
'Static friction adjusts up to a maximum; kinetic friction is modelled as μkN while sliding. The normal force is not automatically mg. On a simple incline with no other normal force component, it is mg cos θ.',
'A sliding object with N=50 N and μk=0.2 has a friction magnitude of 10 N opposite relative sliding.',
'Friction changes both the force balance and energy bookkeeping in motion models.', 'trigonometry',
{'educator':[7],'pearson':[13],'book':[8]},
q('Find kinetic friction when μk=0.3 and N=40 N.',12,'fk=μkN=0.3·40.','N'),
q('An object slides on a horizontal surface. N=60 N, μk=0.2, applied force=30 N forward. Find the net forward force.',18,'Friction is 12 N, so net force is 30−12.','N')),
topic('energy','Work energy and power','Use an energy balance with a defined system.',
'Work transfers energy through force and displacement. For a constant force, W=Fd cos θ. Net work changes kinetic energy. Power is the rate of energy transfer, not an amount of energy.',
'A force of 10 N acting along 3 m does 30 J of work. Delivering 120 J over 4 s corresponds to an average power of 30 W.',
'Power and efficiency language is useful for understanding pumps and motors, while the actual model still needs correct system boundaries.', 'algebra',
{'educator':[15,16],'pearson':[18,19,20,22],'book':[11,12,13]},
q('A constant force of 15 N acts along a displacement of 2 m. Find its work.',30,'W=Fd=15·2.','J'),
q('A motor transfers 600 J in 5 s. Find its average power.',120,'P=W/Δt=600/5.','W')),
topic('momentum','Impulse and momentum','Choose a system and keep velocity signs.',
'Momentum is mv and impulse is the change in momentum. Momentum conservation applies to a system with negligible external impulse over the interval. Kinetic energy need not be conserved in a collision.',
'A 2 kg body changes velocity from +3 to −1 m/s. Its momentum change is 2(−1−3)=−8 kg·m/s.',
'A force-time graph gives impulse by its signed area; the peak force alone does not describe the full effect.', 'graphs',
{'educator':[9,10],'pearson':[23,24,25,26],'book':[14,15]},
q('A 3 kg object travels at +4 m/s. Find its momentum.',12,'p=mv=3·4.','kg·m/s'),
q('A 2 kg body changes velocity from +5 to +2 m/s. Find its impulse, with right positive.',-6,'J=Δp=2(2−5)=−6.','N·s')),
topic('circular-motion','Circular motion','Recognise that changing direction requires acceleration.',
'In uniform circular motion, speed is constant but velocity changes direction. Inward acceleration is v²/r. The required net inward force is supplied by actual forces such as tension, friction or gravity; it is not an additional force.',
'For speed 4 m/s and radius 2 m, inward acceleration is 16/2=8 m/s².',
'Rotating equipment provides context for distinguishing speed, angular motion and inward acceleration.', 'algebra',
{'educator':[11,13],'pearson':[16,17],'book':[9,17]},
q('Find inward acceleration at v=6 m/s and r=3 m.',12,'ac=v²/r=36/3.','m/s²'),
q('A 2 kg object travels in a circle of radius 4 m at 4 m/s. Find net inward force.',8,'F=mv²/r=2·16/4.','N')),
topic('lab-graphs','Laboratory graphs and evidence','Describe a measured relationship without overstating it.',
'Label axes with quantities and units. A straight-line slope is a ratio of changes, with units from the axes. Repeated measurements reveal scatter; they do not by themselves remove calibration error. Record observations separately from explanations.',
'On a position-time graph, points (1 s, 2 m) and (3 s, 8 m) give average slope (8−2)/(3−1)=3 m/s.',
'A reproducible laboratory record states what was measured, how it was measured and the model used to interpret it.', 'graphs',
{'educator':[1,3],'pearson':[2,5],'book':[1,3]},
q('A position-time graph passes through (0 s, 1 m) and (2 s, 7 m). Find the average slope.',3,'Slope=(7−1)/(2−0).','m/s'),
q('A force-versus-extension graph passes through (0.02 m, 4 N) and (0.06 m, 12 N). Find its slope.',200,'Slope=(12−4)/(0.06−0.02)=200.','N/m')),
]

CHEMISTRY = [
topic('atomic-structure','Atomic structure','Count protons neutrons and electrons consistently.',
'Atomic number counts protons. Mass number counts protons plus neutrons. Ion formation changes the electron count, while changing neutrons produces a different isotope. Read superscripts and charge separately.',
'An ion with atomic number 11, mass number 23 and charge +1 contains 11 protons, 12 neutrons and 10 electrons.',
'Composition and charge are the starting information for every later chemical balance.', 'algebra',
{'educator':[3,4],'pearson':[3],'book':[4]},
q('An atom has mass number 23 and atomic number 11. How many neutrons?',12,'Neutrons=23−11.'),
q('An ion has atomic number 12 and charge +2. How many electrons?',10,'A 2+ ion has lost two electrons: 12−2.')),
topic('quantum-theory','Quantum theory','Connect light energy and the electronic model.',
'Photons have energy E=hf=hc/λ. Shorter wavelength means higher photon energy. Atomic electrons occupy allowed energy states; orbitals describe probability rather than miniature planetary paths.',
'If wavelength is halved, photon energy doubles because E is inversely proportional to λ.',
'Spectroscopy uses the relation between absorbed or emitted light and changes in electronic energy.', 'algebra',
{'educator':[13,14,15],'pearson':[20,21],'book':[13,14]},
q('A photon wavelength is halved. What is the ratio Enew/Eold?',2,'E=hc/λ, so half the wavelength gives twice the energy.'),
q('Photon frequency triples. What is the ratio Enew/Eold?',3,'E=hf, so energy scales directly with frequency.')),
topic('periodic-table','Periodic table','Use electron arrangement to explain trends.',
'Across a period, increasing effective nuclear attraction generally reduces atomic radius and raises first ionisation energy. Down a group, additional occupied shells usually increase size. Exceptions need electron-configuration reasoning.',
'An electron arrangement 2,8,1 has one outer-shell electron. Losing that electron gives a common +1 ion.',
'Valence behaviour helps predict bonding and reactivity before a reaction is tested.', 'algebra',
{'educator':[15,16],'pearson':[21,22],'book':[14,15]},
q('For an atom with shell arrangement 2,8,1, how many electrons are in the outer shell?',1,'The final occupied shell contains one electron.'),
q('For a main-group atom with shell arrangement 2,8,7, how many electrons are needed to complete an octet?',1,'An octet contains eight electrons, so 8−7=1.')),
topic('bonding','Chemical bonding','Account for electrons before assigning shape and polarity.',
'Count valence electrons, connect atoms, distribute electrons and check formal charges. Electron-domain geometry and molecular shape are different when lone pairs are present. Molecular polarity depends on both bond polarity and shape.',
'CO₂ has 4+2(6)=16 valence electrons. Two double bonds give a linear arrangement; equal opposite bond dipoles cancel.',
'Bonding and molecular shape help explain properties used in separation and material selection.', 'algebra',
{'educator':[17,18,19,20],'pearson':[23,24],'book':[16,17]},
q('How many valence electrons are present in neutral CO₂? Carbon has 4 and oxygen 6.',16,'4+2·6=16.'),
q('How many valence electrons are present in neutral H₂O? Hydrogen has 1 and oxygen 6.',8,'2·1+6=8.')),
topic('aqueous-reactions','Reactions in solution','Use balanced amounts and identify reacting species.',
'Balance atoms and charge before applying mole ratios. Strong soluble electrolytes can be represented as ions; spectator ions cancel in a net ionic equation. Available amounts determine the limiting reactant.',
'For Ag⁺+Cl⁻→AgCl(s), 0.10 mol Ag⁺ needs 0.10 mol Cl⁻. With only 0.06 mol Cl⁻, at most 0.06 mol precipitate can form.',
'Reactant amounts set the maximum material conversion, even when the equation is correctly balanced.', 'algebra',
{'educator':[8,9,10,11,12],'pearson':[7,8,9,11,13],'book':[8,9,11,12]},
q('For 2H₂+O₂→2H₂O, how many moles of water can 3 mol H₂ form with excess O₂?',3,'The H₂:H₂O mole ratio is 2:2.','mol'),
q('For Ag⁺+Cl⁻→AgCl, mix 0.20 mol Ag⁺ and 0.12 mol Cl⁻. Find the maximum amount of AgCl.',0.12,'The ratio is 1:1 and chloride is limiting.','mol')),
topic('solutions','Properties of solutions','Choose a concentration measure and preserve solute amount.',
'Molarity is amount of solute divided by solution volume in litres. For dilution of the same solute without reaction or loss, the amount stays constant: M₁V₁=M₂V₂. Intermolecular interactions and dissolved particle count influence solution properties.',
'Dissolving 0.20 mol to make 0.50 L of solution gives 0.40 mol/L. Adding solvent lowers molarity without changing the solute amount.',
'Concentration links the volume of a process stream to the amount of material it carries.', 'algebra',
{'educator':[30,31],'pearson':[10,27,28],'book':[10,22]},
q('Find molarity for 0.30 mol solute in 0.50 L of solution.',0.6,'M=n/V=0.30/0.50.','mol/L'),
q('A 0.20 L sample of 1.5 mol/L solution is diluted to 0.60 L. Find final molarity.',0.5,'M₂=M₁V₁/V₂=1.5·0.20/0.60.','mol/L')),
topic('gases','Properties of gases','Use absolute temperature and state model assumptions.',
'The ideal gas equation PV=nRT relates state variables. Use compatible units and temperature in kelvin. At constant amount and temperature, pressure varies inversely with volume. Real gases depart from ideal behaviour, especially when interactions or molecular volume matter.',
'For a fixed ideal-gas amount at fixed temperature, reducing volume from 4 L to 2 L doubles pressure.',
'Gas calculations require a stated pressure basis and temperature; a number without conditions is incomplete.', 'units',
{'educator':[22,23],'pearson':[15,16,17],'book':[20]},
q('An ideal gas at 2 bar occupies 3 L. At constant temperature it is compressed to 1.5 L. Find pressure.',4,'P₁V₁=P₂V₂ gives 2·3/1.5.','bar'),
q('At constant volume and amount, an ideal gas changes from 300 K and 100 kPa to 450 K. Find pressure.',150,'P₂/P₁=T₂/T₁=450/300.','kPa')),
topic('thermochemistry','Thermochemistry','Keep system heat and reaction signs consistent.',
'For a temperature change with no phase transition, q=mcΔT. A system receiving heat has positive q. In an ideal insulated calorimetry balance, heat lost by one part equals heat gained by the other. Reversing a reaction reverses its enthalpy sign.',
'Heating 100 g of a substance with c=4 J/(g·°C) by 5°C requires q=100·4·5=2000 J.',
'Energy balances begin by specifying which system a sign describes; heat and temperature are different quantities.', 'algebra',
{'educator':[27,28],'pearson':[18,19],'book':[18,19]},
q('Find q for 50 g, c=2 J/(g·°C), and a temperature rise of 3°C.',300,'q=mcΔT=50·2·3.','J'),
q('A reaction has ΔH=−120 kJ as written. Find ΔH for the reverse reaction.',120,'Reversing the reaction reverses the sign.','kJ')),
topic('electrochemistry','Electrochemistry','Track oxidation reduction and the cell-potential convention.',
'Oxidation loses electrons at the anode; reduction gains electrons at the cathode. With tabulated reduction potentials, E°cell=E°cathode−E°anode. Do not multiply an electrode potential by a balancing coefficient. Electrolysis relates charge to electron amount.',
'Using cathode reduction potential +0.34 V and anode reduction potential −0.76 V gives E°cell=1.10 V.',
'Electrochemical reasoning supports later study of corrosion, electrolysis and energy conversion.', 'algebra',
{'educator':[41,42],'pearson':[41,42,43],'book':[33,34]},
q('Cathode and anode reduction potentials are +0.50 V and −0.20 V. Find E°cell.',0.7,'E°cell=0.50−(−0.20).','V'),
q('Cathode and anode reduction potentials are +0.80 V and −0.40 V. Find E°cell.',1.2,'E°cell=0.80−(−0.40).','V')),
]

COURSES = [
 dict(id='ma101',path='math',code='MA 101',title='Calculus I',credits=4,tag='Change and mathematical models',scope='Limits, continuity, derivatives, rates of change, approximations, optimization, curve sketching, Rolle’s theorem and the Mean Value Theorem.',status='Published topics; proposed study order',topics=MATH),
 dict(id='phy101',path='physics',code='PHY 101',title='General Physics I',credits=4,tag='Motion forces and physical evidence',scope='Fundamentals of physics, laws of motion, applications, laboratory experiments and graphing skills. The detailed mechanics sequence below is provisional until the lecturer’s outline is available.',status='Broad published scope; provisional topic breakdown',topics=PHYSICS),
 dict(id='chemistry',path='chemistry',code='CHEM 101',title='General Chemistry I',credits=4,tag='Matter reactions and energy',scope='Atomic structure, quantum theory, periodic table, chemical bonds, reactions in solution, properties of solutions and gases, thermochemistry and electrochemistry.',status='Published topics; proposed study order',topics=CHEMISTRY),
]

FOUNDATIONS = {
 'algebra': ('Algebra repair','Rearrange an equation by applying the same valid operation to both sides. Keep domain restrictions when dividing or taking roots. For products and fractions, simplify structure before inserting numbers.','From y=mx+b with m≠0, x=(y−b)/m. If y=11, m=3 and b=2, then x=3.','Solve 5x+2=17.','x=3. Subtract 2, then divide by 5.'),
 'trigonometry': ('Trigonometry repair','Resolve a vector relative to a stated angle. If θ is measured from the positive horizontal axis, x=A cos θ and y=A sin θ. Use radians for calculus derivative rules.','A vector of magnitude 10 at 60° to the horizontal has horizontal component 5.','Find the horizontal component of a magnitude-8 vector at 60°.','8 cos 60° = 4.'),
 'graphs': ('Graphs and functions','Read axes and units first. A slope is vertical change divided by horizontal change. A function value, slope and area represent different things. Check whether the question asks for an average over an interval or a local value.','Points (1,3) and (4,9) give slope (9−3)/(4−1)=2.','Find the slope through (2,5) and (6,13).','(13−5)/(6−2)=2.'),
 'units': ('Units and scientific notation','Multiply conversion factors equal to one so unwanted units cancel. Temperature in an ideal-gas ratio must use kelvin. Keep powers of ten and prefix conversions visible.','0.025 L × 1000 mL/L = 25 mL. Also, 25°C = 298.15 K.','Convert 0.15 kg to grams.','0.15 × 1000 = 150 g.'),
 'logs': ('Exponents and logarithms','For positive a and b, ln(ab)=ln a+ln b. A logarithm reverses its matching exponential. These rules do not allow ln(a+b)=ln a+ln b.','ln(e³)=3 and 10²=100. A logarithm input must be positive.','Find log₁₀(1000).','3, because 10³=1000.'),
}
